{"name": "test_playWright", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nPlease use the Async API instead.", "trace": "def test_playWright():\n>       playwright = sync_playwright().start()\n\ntestcases/test_playWright.py:7: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../test/.venv/lib/python3.8/site-packages/playwright/sync_api/_context_manager.py:84: in start\n    return self.__enter__()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright.sync_api._context_manager.PlaywrightContextManager object at 0x7fca41ddd790>\n\n        def __enter__(self) -> SyncPlaywright:\n            try:\n                self._loop = asyncio.get_running_loop()\n            except RuntimeError:\n                self._loop = asyncio.new_event_loop()\n                self._own_loop = True\n            if self._loop.is_running():\n>               raise Error(\n                    \"\"\"It looks like you are using Playwright Sync API inside the asyncio loop.\n    Please use the Async API instead.\"\"\"\n                )\nE               playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nE               Please use the Async API instead.\n\n../test/.venv/lib/python3.8/site-packages/playwright/sync_api/_context_manager.py:47: Error"}, "start": 1720082789278, "stop": 1720082789278, "uuid": "50176543-6ea3-4c50-9e0d-96c8c8e85a97", "historyId": "dc81b87cffcf1dff45de633ad03b643a", "testCaseId": "dc81b87cffcf1dff45de633ad03b643a", "fullName": "testcases.test_playWright#test_playWright", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_playWright"}, {"name": "host", "value": "shiyingdeMBP"}, {"name": "thread", "value": "3756-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_playWright"}]}